### ISSUE TITLE
Revisar proceso de borrado de una red y el IndexWorker

### ISSUE THREAD

**Issue by lareferencia** [lareferencia/main#116]
Volcado de test BR

``` log
Comenzando proceso de borrando Red: ABHR
Borrando Snapshot: 2
Borrando registros de validaciones
Borrando stadísticas de metadatos
Borrando registros de log
Borrando registros de metadatos
Borrando Snapshot: 1
Borrando registros de validaciones
Borrando stadísticas de metadatos
Borrando registros de log
Borrando registros de metadatos
Borrando Origenes/Sets
Borrando la red del índice
Finalizando borrado red: ABHR
Indexer Worker - El id de red es inválido
2015-05-13 15:39:13,420 ERROR ng.support.TaskUtils$LoggingErrorHandler:  95 - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
    at org.lareferencia.backend.indexer.IndexerWorker.run(IndexerWorker.java:66) ~[IndexerWorker.class:na]
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_75]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_75]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

```

**Comment by lareferencia** [comment]
Hay que resolver el problema generado por el borrado del Network que luego es leído desde el IndexerWorker. Probablemente haya que crear un parámetro que no esté relacionado con el objeto persistido para evitar problemas de sincronización.
